### ISSUE TITLE
Multiple operations per effect (?)

### ISSUE THREAD

**Issue by stepchowfun** [stepchowfun/delimited-effects#29]
Do we want to bother?

**Comment by stepchowfun** [comment]
No.

**Comment by atennapel** [comment]
Wouldn't you need get and set operations for a state effect?

**Comment by stepchowfun** [comment]
@atennapel Thanks for your comment. The intention of closing this issue was not to signal that multiple operations per effect are not needed/wanted, but rather that they don't add anything interesting to the typing rules or semantics (after some reflection, I might be wrong about the latter). So we were considering formalizing the core system in terms of one operation per effect (similar to the original type classes paper by Wadler and Blott), and only discussing multiple operations informally in examples, prose, etc. Once the formalization is complete, it should be easy (we predict) to extend to support multiple operations per effect—and we'll probably do it if it's not too ugly.

I think neither of us have had a chance to think about whether this restriction comes with a loss of generality. Thanks for linking to that Stack Exchange post—I hadn't seen it before. I was under the impression that we could encode multiple operations as a single operation which is a product, and we will have to reconcile that with Andrej Bauer's response.

It's clear now that this issue has some interesting substance to it, so I'm re-opening it.
