### ISSUE TITLE
Work on formalization of effect masking

### ISSUE THREAD

**Issue by ewang12** [stepchowfun/delimited-effects#37]
For instance, do we need contravariance in EM-Arrow?

**Comment by ewang12** [comment]
We concluded that we don't need contravariance in EM-Arrow.

How can we formalize effect masking so that an inference algorithm follows naturally?

**Comment by stepchowfun** [comment]
> How can we formalize effect masking so that an inference algorithm follows naturally?

Closing because @ewang12 solved this in https://github.com/stepchowfun/delimited-effects/commit/02ea92fd1f68ee81259b5c6e042315d1f6ac0621.
