### ISSUE TITLE
Replace the effect row equivalence relation with a preorder?

### ISSUE THREAD

**Issue by stepchowfun** [stepchowfun/delimited-effects#43]
I think this will simplify some things. We won't have to have `E4` in `EM-Unit`, `EM-Arrow`, or `T-Application`. What do you think @ewang12?

**Comment by ewang12** [comment]
I don't see any reason not to. Let's change it!

**Comment by ewang12** [comment]
Changed in 26c7aa520ad34f15269882ec30d57cba0b8b2322.
